### ISSUE TITLE
doesnt seem to install

### ISSUE THREAD

**Issue by DemonsOfChaos** [ZANdewanai/Genshin-Impact-Rich-Presence#13]
when i try to install from the .exe or .bat, it gives me these errors then immediately closes. not really sure what they mean lol
![Screenshot 2024-10-14 131806](https://github.com/user-attachments/assets/6b633083-9111-4b4c-938b-9f203bae115d)

**Comment by DemonsOfChaos** [comment]
been using this for a couple months and i havent had any problems until now. shouldnt of reinstalled i guess

**Comment by ZANdewanai** [comment]
it says you have to install torch for python again, i dont quite remember if any version is fine or if its a specific one but well thats the issue

**Comment by ZANdewanai** [comment]
to do that just open a cmd and paste this
pip install torch
![image](https://github.com/user-attachments/assets/aabafa88-a9e0-4278-ac26-0c2e69011b51)

**Comment by ZANdewanai** [comment]
should look like that if you do
pip list
afterwards
(you may need to install torchvision too)
![image](https://github.com/user-attachments/assets/15b471f2-532b-4d81-ac03-dcda20ce5efa)

**Comment by ZANdewanai** [comment]
been so long since i looked at this rich presence lol
